### PR TITLE
Add SleeperStacks() function to FakeClock to allow for easier debugging.

### PR DESCRIPTION
**Pull request by arya**

### CODE REVIEW

**Comment by jonboulle** [comment]
I guess this was from an old master..? quite a few merge conflicts

**Comment by arya** [comment]
@jonboulle sorry about that, I had made the changes on my vendored version and just copied clockwork.go over. My bad :) I've fixed it to apply to the latest master.

**Comment by jonboulle** [comment]
For a little more context would you mind providing an example use case (or linking me to somewhere you're using this?)

**Comment by arya** [comment]
It's purely for debugging. An example use case is that you have a call to BlockUntil(5) and it sometimes never returns. Using SleeperStacks(), you can see what the current blockers are to confirm they are what you expect or discover that one is missing or that there is an additional one.

**Pull request closed without merging**
