### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by rockspore**

### CODE REVIEW

**Comment by DPJacques** [comment]
Thanks for the fix. Sadly, I don't have permissions to merge it in :(

**Comment by rockspore** [comment]
Thanks. I just wanted to get rid of the warning from my IDE :)

Is there no maintainer that regularly checks this repo? Also curious why you haven't been permitted the access to approve the workflow? ;-)

**Comment by DPJacques** [comment]
I have worked with @sagikazarmark to date. He has always been quite helpful. He is also more knowledgeable about Github workflows than I am.

I wasn't actively contributing to open source code until relatively recently.

**Review by sagikazarmark — APPROVED** [review]
Thank you @rockspore

**Pull request merged**
